### ISSUE TITLE
Sometimes Snackbar does not shows until I kill the app

### ISSUE THREAD

**Issue by tuhin10** [AndreiD/TSnackBar#10]
I am running on android lollipop

**Comment by tuhin10** [comment]
Steps to replicate the issue:

In activity A while TSnackBar is shown goto Activity B, try to show TSnackBar . But TSnackBar refuses to show up.

**Comment by henriquedesousa** [comment]
I already face this too, it's weird.

**Comment by henriquedesousa** [comment]
I already face this too, it's weird. Unfortunately I will stop using this library because of this bug, I really cannot use this in production. My issue is a bit different, I'm using it inside a Fragment that's replaced on an old DrawerLayout, but I don't need to kill the app to make it reappear, seems I just have to wait a while, it's really weird but it's reproducable. What can I do to help?

**Comment by AndreiD** [comment]
so I would start like I originally started: get the sources from snackbar (the original one) and modify the gravity of it to be from top.

**Comment by AndreiD** [comment]
update to the latest version.
